version: '2'
services:
  
  fusiondirectory-app-:
    container_name: fusiondirectory-app
    restart: always
    image: tiredofit/fusiondirectory:debian
    depends_on:
      - openldap-fusiondirectory
    environment:
      - VIRTUAL_HOST=fusiondirectory.example.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=fusiondirectory.example.org
      - LETSENCRYPT_EMAIL=yourname@example.org

      - ZABBIX_HOSTNAME=fusiondirectory-app

      - LDAP_DOMAIN=example.org
      - LDAP_HOST=openldap-fusiondirectory
      - LDAP_ADMIN_PASSWORD=password
    volumes:
      # Can also create just specific files following structure to map to ./custom:/assets/fusiondirectory
      - ./custom:/usr/share/fusiondirectory
    networks:
      - proxy-tier


networks:
  proxy-tier:
    external:
      name: nginx-proxy


